name: myapp
description: "App para registro de infracciones"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.13.2
  firebase_storage: ^13.0.6
  flutter_native_splash: ^2.4.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#F52784"
  adaptive_icon_foreground: "assets/icon/logo.png"

flutter_native_splash:
  color: "#0D0D0D"
  image: assets/icon/logo.png
  android_12:
    image: assets/icon/logo.png
    color: "#0D0D0D"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png